name: opensense-training-school
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cartopy
  - jsmin
  - jsonschema
  - matplotlib
  - netCDF4
  - numpy
  - opencv
  - pillow
  - pyproj
  - rasterio
  - scipy
  - xarray
  - rioxarray
  - jupyter
  - jupyterlab
  - pysteps
